@baseUrl = http://localhost:5050/api

### ===================== DEPARTMENT =====================
POST {{baseUrl}}/department
Content-Type: application/json

{
  "name": "Management"
}

### ===================== COURSE PROGRAM =====================
POST {{baseUrl}}/program
Content-Type: application/json

{
  "name": "BBA",
  "duration": 3,
  "departmentId": 18
}

###
POST {{baseUrl}}/program
Content-Type: application/json

{
  "name": "MBA",
  "duration": 2,
  "departmentId": 18
}

###
POST {{baseUrl}}/program
Content-Type: application/json

{
  "name": "PhD",
  "duration": 3,
  "departmentId": 18
}

### ===================== SEMESTER =====================
POST {{baseUrl}}/semester
Content-Type: application/json

{
  "semesterName": "Semester 1",
  "programId": 53
}

###
POST {{baseUrl}}/semester
Content-Type: application/json

{
  "semesterName": "Semester 2",
  "programId": 53
}
###
POST {{baseUrl}}/semester
Content-Type: application/json

{
  "semesterName": "Semester 3",
  "programId": 53
}
###
POST {{baseUrl}}/semester
Content-Type: application/json

{
  "semesterName": "Semester 4",
  "programId": 53
}
###
POST {{baseUrl}}/semester
Content-Type: application/json

{
  "semesterName": "Semester 5",
  "programId": 52
}
###
POST {{baseUrl}}/semester
Content-Type: application/json

{
  "semesterName": "Semester 6",
  "programId": 52
}

### ===================== CLASS =====================
POST http://localhost:5050/api/seed/class
Content-Type: application/json

{
  "className": "CS-C",
  "capacity": 60,
  "semesterId": 3
}

### ===================== SUBJECT =====================
POST {{baseUrl}}/subject
Content-Type: application/json

{
  "name": Basic Electrical Engineering",
  "credits": 4
}

### ===================== USER (FOR TEACHER / ADMIN) =====================
POST {{baseUrl}}/user
Content-Type: application/json

{
  "email": "teacher3@gmail.com",
  "password": "123456",
  "role": "Teacher"
}

### ===================== TEACHER =====================
POST {{baseUrl}}/teacher
Content-Type: application/json

{
  "userId": 1,
  "teacherId": 101,
  "teacherName": "Dr. Sharma",
  "departmentId": 1
}

### ===================== CLASS SEMESTER SUBJECT =====================
POST {{baseUrl}}/class-subject
Content-Type: application/json

{
  "classId": 1,
  "semesterId": 1,
  "subjectId": 1,
  "teacherId": 1
}

### ===================== STUDENT =====================
POST {{baseUrl}}/student
Content-Type: application/json

{
  "userId": 2,
  "fullName": "Manoj",
  "universityRollNo": 1001,
  "classRollNo": 1,
  "classId": 1
}

### ===================== ATTENDANCE =====================
POST {{baseUrl}}/attendance
Content-Type: application/json

{
  "studentId": 1,
  "classSubjectId": 1,
  "isPresent": true
}

###
GET http://localhost:5050/api/department
Content-Type: application/json
{

}

###
GET http://localhost:5050/api/program/by-department/18
Content-Type: application/json
{
}

###
GET http://localhost:5050/api/semester/by-program/1
Content-Type: application/json
{
}


###
GET http://localhost:5050/api/class/by-semester/1
Content-Type: application/json
{
}

###
GET http://localhost:5050/api/student/by-class/1
Content-Type: application/json
{
}

###=============LOGIN==================================
POST http://localhost:5050/api/auth/login
Content-Type: application/json
{
  "Email": "student@gmail.com",
  "Password": "1234567"
}

###
GET http://localhost:5050/api/class/1/subjects
Content-Type: application/json
{
  
}



### 5) Logged-in student self attendance
GET http://localhost:5050/api/attendance/student/attendance
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJzdHVkZW50QGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlN0dWRlbnQiLCJleHAiOjE3NzU4MjkwNTIsImlzcyI6IkVSUFN5c3RlbSIsImF1ZCI6IkVSUFVzZXJzIn0.tZ2fEAIw20gl9BI9ioy2CRotvoHGa6W6YzBVxGTGbno

###
GET http://localhost:5050/api/attendance/student/1/class/1/overview
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJzdHVkZW50QGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlN0dWRlbnQiLCJleHAiOjE3NzU4MjkwNTIsImlzcyI6IkVSUFN5c3RlbSIsImF1ZCI6IkVSUFVzZXJzIn0.tZ2fEAIw20gl9BI9ioy2CRotvoHGa6W6YzBVxGTGbno
